# Generated by Django 2.2.1 on 2019-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
